language: python
services:
  - docker
before_install:
  - pip install awscli
  - sudo apt-get install dos2unix -y
  - export PATH=$PATH:$HOME/.local/bin
  - dos2unix -R ./*

script:
  - docker build -t $DOCKER_REPO_NEW .

deploy:
  provider: script
  script: bash deploy/ecr.sh
  on:
    branch: master