"""Removed unecessary tables

Revision ID: 02652d97c39c
Revises: 39ed237be5f5
Create Date: 2019-08-02 14:26:14.411624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02652d97c39c'
down_revision = '39ed237be5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('client_secret', table_name='api_auth')
    op.drop_table('api_auth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_auth',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.VARCHAR(collation='latin1_bin', length=100), nullable=False),
    sa.Column('client_secret', mysql.VARCHAR(collation='latin1_bin', length=400), nullable=False),
    sa.Column('api_calls', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_bin',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('client_secret', 'api_auth', ['client_secret'], unique=True)
    # ### end Alembic commands ###
