"""empty message

Revision ID: 0e08b5ac1521
Revises: 7fc0d57cabb8
Create Date: 2017-10-24 10:47:16.876737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e08b5ac1521'
down_revision = '7fc0d57cabb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shortto')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'big5',
    mysql_engine=u'InnoDB'
    )
    op.create_table('shortto',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('big_url', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('short_url', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'shortto_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'big5',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
