"""Added google login bool

Revision ID: 269974850bc8
Revises: 827933f22687
Create Date: 2019-08-02 09:57:11.465926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269974850bc8'
down_revision = '827933f22687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_login', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'google_login')
    # ### end Alembic commands ###
