"""Removed google id

Revision ID: 39ed237be5f5
Revises: 269974850bc8
Create Date: 2019-08-02 10:51:51.468990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39ed237be5f5'
down_revision = '269974850bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('google_id', table_name='user')
    op.drop_column('user', 'google_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('google_id', 'user', ['google_id'], unique=True)
    # ### end Alembic commands ###
