"""empty message

Revision ID: 68b2a4789556
Revises: 
Create Date: 2019-08-29 11:20:39.380778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68b2a4789556'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('firstName', sa.String(length=130), nullable=True),
    sa.Column('lastName', sa.String(length=130), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('picture', sa.String(length=200), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('personal_phone', sa.String(length=20), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmationHash', sa.String(length=1000), nullable=True),
    sa.Column('google_login', sa.Boolean(), nullable=True),
    sa.Column('locale', sa.String(length=30), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bundle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('archieved', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('big_url', sa.String(length=1000), nullable=False),
    sa.Column('short_url', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=20), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('password_protect', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=250), nullable=True),
    sa.Column('expiration', sa.Boolean(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('archieved', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bundle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_url')
    )
    op.drop_index('short_url', table_name='shortto')
    op.drop_table('shortto')
    op.drop_index('client_secret', table_name='api_auth')
    op.drop_table('api_auth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_auth',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('client_secret', mysql.VARCHAR(length=400), nullable=False),
    sa.Column('api_calls', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('client_secret', 'api_auth', ['client_secret'], unique=True)
    op.create_table('shortto',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('big_url', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('short_url', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('clicks', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('short_url', 'shortto', ['short_url'], unique=True)
    op.drop_table('links')
    op.drop_table('bundle')
    op.drop_table('announcement')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
