"""empty message

Revision ID: 7fc0d57cabb8
Revises: 
Create Date: 2017-10-24 10:25:56.934060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fc0d57cabb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrate_version')
    op.drop_table('shortto')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'big5',
    mysql_engine=u'InnoDB'
    )
    op.create_table('shortto',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('big_url', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('short_url', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'big5',
    mysql_engine=u'InnoDB'
    )
    op.create_table('migrate_version',
    sa.Column('repository_id', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('repository_path', mysql.TEXT(), nullable=True),
    sa.Column('version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('repository_id'),
    mysql_default_charset=u'big5',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
