"""Added new conf hash

Revision ID: ca54449c3a9c
Revises: d0e13a8de7d7
Create Date: 2019-08-08 14:28:34.323091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca54449c3a9c'
down_revision = 'd0e13a8de7d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmationHash', sa.String(length=1000), nullable=True))
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    op.drop_column('user', 'confirmationHash')
    # ### end Alembic commands ###
