"""Added Link created at

Revision ID: d744732a30a1
Revises: 02652d97c39c
Create Date: 2019-08-02 15:21:39.384504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd744732a30a1'
down_revision = '02652d97c39c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'created_at')
    # ### end Alembic commands ###
